### ISSUE TITLE
vmware build fails

### ISSUE THREAD

**Issue by sjourdan** [sjourdan/ubuntu-1404-ucp-packer#2]
probably linked to missing kernel headers or something

```
    vmware: VMware Tools 9.6.6 build-2649738 for Linux installer
    vmware: Usage: /tmp/vmware-tools-distrib/vmware-install.pl [[-][-]d[efault]]
    vmware: default: Automatically answer questions with the proposed answer.
    vmware: [[-][-]prefix=<path to install product: bin, lib, doc>]    Put the installation
    vmware: at <path> instead of the default location.  This implies '--default'.
    vmware: --clobber-kernel-modules=<module1,module2,...>    Forcefully removes any VMware
    vmware: related modules installed by any other installer and installs the modules
    vmware: provided by this installer.  This is a comma seperated list of modules.
    vmware:
    vmware: /tmp/script_7943.sh: line 13: /etc/vmware-tools/locations: No such file or directory
Build 'vmware' errored: Script exited with non-zero exit status: 1
```
